Create english version of the current german RC text
isaqb-org/curriculum-api pull request #39
Opened 2024-12-29 22:51 UTC by dret

Here's a first version of the English translation of the current version. My plan is to use this as a good opportunity to publicize the curriculum a little better, and maybe iSAQB can help with that, @programming-wolf / @StefanZoerner ?

It also would be great to have this being incorporated in an updated RC better sooner than later. @sippsack, after this PR has been approved and merged, would you be so kind to do your tagging magic again? After that we should have a first complete version available at https://public.isaqb.org/curriculum-api/release-candidate/ which would be a good starting point for making a bit of noise about the RC.

2025-01-13 21:51 UTC, thfro requested changes
Spotted some typos and added very one or two questions.

2025-01-13 21:51 UTC, thfro commented on docs/06-api-lifecycle/02-learning-goals.adoc
> +Participants know typical tools that are used throughout the API lifecycle. These tools support producers as well as consumers and include functionality such as linting, testing (e.g., contract testi
Remove "add" in front of "mocking"

2025-01-13 21:51 UTC, thfro commented on docs/06-api-lifecycle/02-learning-goals.adoc
> +Participants gain some practical knowledge of some of these tools and understand how the fit into the bigger picture of API lifecycle tooling.
gain some knowledge -> gain knowledge
how the fit -> how they fit

2025-01-13 21:51 UTC, thfro commented on docs/07-api-security/02-learning-goals.adoc
> +Participants understand how HTTPS, HTTP authentication, OAuth, and OpenID Connect, how they relate and differ, and how these technologies heklp when it comes to securing APIs.
understand how HTTP -> understand HTTP
heklp -> help

2025-01-13 21:51 UTC, thfro commented on docs/08-api-governance/02-learning-goals.adoc
> +Participants understand the various areas in which the notion of platforms are being used. They understand how these notions different and how they complement each other.
notions different -> notions differ / notions are different

2025-01-13 21:51 UTC, thfro commented on docs/08-api-governance/02-learning-goals.adoc
> +Participants understand the motivation for API guidelines. They understand the goals of creating harmonized practices for both API design and the implementation practices for APIs. Tools for supporti
are know -> are known

2025-01-13 21:51 UTC, thfro commented on docs/08-api-governance/02-learning-goals.adoc
> +Participants know some well-known examples of API guidelines by specific organizations. They also know good practices for managing and evolving API guidelines. Participants understand API guidelines
that managed -> that is managed

2025-01-13 21:51 UTC, thfro commented on docs/08-api-governance/02-learning-goals.adoc
> +Participants know Team Topologies as an organizational model for making team work more effective. The specific focus is on understanding how APIs are necessary to make the Team Topologies model work.
making team -> making teams

2025-01-13 21:58 UTC, dret commented on docs/05-api-description/02-learning-goals.adoc
> +
Sounds fine with me but seems to drill down a level deeper than we often go. If we drill down here does that imply we have to drill down everywhere else as well?

2025-01-13 22:00 UTC, dret commented on docs/05-api-description/01-duration-terms.adoc
> +API-Beschreibung, OpenAPI, protocol buffers, AsyncAPI, GraphQL
Maybe that's true and it's a fixed term?

2025-01-13 22:01 UTC, dret commented on docs/08-api-governance/02-learning-goals.adoc
> +Participants understand the various areas in which the notion of platforms are being used. They understand how these notions different and how they complement each other.
probably "are different" is the better fix here.

2025-01-13 22:04 UTC, thfro commented on docs/05-api-description/02-learning-goals.adoc
> +
Fair point. Just thinking we should not leave the concept of code generation uncommented. Perhaps we could rephrase to:  "Participants understand how to use OpenAPI for code generation both on the provider side and on the consumer side, and that this practice has some risks."

2025-01-15 09:58 UTC, sippsack reviewed
01-what-to-expect-of-this-module.adoc is missing english translation

2025-01-15 09:58 UTC, sippsack commented on docs/01-why-apis/02-learning-goals.adoc
> +==== LG 1-1: Understanding APIs in the Context of Software Development
Die meisten Lehrpläne verwenden statt "Unterstanding" "Unterstand" usw. Das werde ich gleich noch angleichen.

2025-01-15 09:58 UTC, sippsack commented on docs/05-api-description/02-learning-goals.adoc
> +
Lasst uns dann dazu einen eigenes Ticket aufmachen und dort diskutieren. Hier geht es um die Übersetzung, da sollten wir nicht noch weitere Themen vermischen

2025-01-15 09:58 UTC, sippsack commented on docs/05-api-description/02-learning-goals.adoc
> +
siehe #40

2025-01-15 09:58 UTC, sippsack commented on docs/06-api-lifecycle/02-learning-goals.adoc
> +APIs are often used in loosely coupled scenarios and for this reason it makes sense to manage them as products.
moved to #41

2025-01-15 10:42 UTC, sippsack approved these changes

2025-01-15 10:42 UTC, sippsack commented on docs/06-api-lifecycle/02-learning-goals.adoc
> +Participants understand the the various stages of planning, requirements analysis, design, prototyping, development, testing, quality assurance, deployment, publication, operations, and maintenance,
the the => the

2025-01-15 10:47 UTC, sippsack commented
I fixed all the typos, created some new issues if the content is not clear enough, added translation for module explanation, time table and prerequisites. 

It looks good so far and I will merge the current state.

2025-01-15 10:51 UTC, merged